### ISSUE TITLE
Docker v2.2.3 Crashing

### ISSUE THREAD

**Issue by joesixpack** [NodleCode/chain#786] opened 2023-09-13 14:47 UTC
```
Version: 2.2.3-f6d58343718

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
      std::panicking::rust_panic_with_hook
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   5: core::panicking::panic_fmt
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   6: fdlimit::raise_fd_limit
   7: sc_cli::config::CliConfiguration::init
   8: sc_cli::SubstrateCli::create_runner
   9: nodle_parachain::command::run
  10: nodle_parachain::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
  14: main
  15: <unknown>
  16: __libc_start_main
  17: _start


Thread 'main' panicked at 'raise_fd_limit: error calling setrlimit: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fdlimit-0.2.1/src/lib.rs:105

This is a bug. Please report it at:

        https://github.com/NodleCode/chain/issues/new
```

**Comment by aliXsed** [comment] 2023-09-13 22:03
@joesixpack thank you submitting this issue. Can you tell us about the docker environment (the host os + the hardware) where this happened? 
The issue is deep in a place not related to nodle-parachain code. It's when the substrate cli is being initialized and checks the limit for the number of open file descriptors.

**Comment by simonsso** [comment] 2023-09-20 00:32
@joesixpack could you please tell us about how you observed this issue so we can reproduce it?

**Comment by aliXsed** [comment] 2023-10-26 21:10
Closing this as we have not enough information to investigate it.

**Closed by aliXsed** 2023-10-26 21:10 UTC
